version: '3.7'
services: 
    database:
        image: postgres:12
        ports: 
            - '35432:5432'
        env_file: 
            - ./server/.env.db
        volumes:
            - database-data:/var/lib/postgresql/data/
volumes: 
    database-data: